### ISSUE TITLE
Values in [UXF_Rig] don't seem to stick

### ISSUE THREAD

**Issue by mrstruijk** [immersivecognition/unity-experiment-framework#107]
Hi!

I noticed in my main project that if I change certain value prior to entering PlayMode in the Rig, they don't seem to affect the behaviour of the Rig.

For instance, if I toggle "Don't Destroy", it still gets destroyed when loading a new scene. I can get the Rig to persist, if I add my own DontDestroyOnLoad script to the object. The code is exactly the same as the one in Session.cs, which confuses me a bit. 

Also, if I first set the Settings Mode in [UXF_UI] to 'Download from URL', and I make a spelling error in the URL (e.g. change the default URL to 'https://giste...' instead of 'https://gist...'), I naturally get an Internal Server Error, which is expected. However, if I then change the Settings Mode to 'Empty', without first fixing my typo, I still get the same Server Error. That only changes if I first fix the typo, and only then set the Settings Mode to 'Empty'.  It looks like the Rig always wants to connect to the URL, regardless of the mode it's on. 

On a brand new Unity Project, when following the same steps, I don't seem to have these issues.

Things I've changed / tried in my main project:
- I've added ASMDefs for the UXF and the UXF.tests (also did this in the new test project, and there it's no prob). 
- Changed the script execution order to have Session be running first. No luck.
- Disabled the SessionEditor, thought that maybe the Editor was not updating the values correctly. No luck.

I'm running UXF Version 2.3.6 on Unity 2021.2.11. 

What else can I try to solve this?

Best, 
Maarten

**Comment by mrstruijk** [comment]
To add to this: If I put the Rig not in the first scene, but in one of the subsequent ones, the DontDestroyOnLoad works fine... The minor issue with the SettingsMode remains the same however.

**Comment by jackbrookes** [comment]
Interesting! I cannot replicate in any of the example scenes.

Question: When you change a value as you described, then save/close the scene (or Unity), and re-open, does the value stick?

My first thought was to enable these settings:
![image](https://user-images.githubusercontent.com/23621596/154352375-6f677cfb-6f13-47ff-a65f-590e76d1a9e6.png)
I suspected it could be an issue related to initialisation performed in Edit mode. But I cannot replicate the behaviour either way.

To further debug, could you see if the Awake methods are being called correctly in UXF.Session & UXF.UIController components? It should run when pressing play. Just slip a Debug.Log in the Awake methods:

![image](https://user-images.githubusercontent.com/23621596/154352803-5b1cead8-cd11-4d52-ae43-b89f546d78f8.png)

**Comment by mrstruijk** [comment]
Well you're right, the Awake doesn't get run from the first scene at all. 

In Session, I added this to Awake:
![Screenshot 2022-02-17 at 12 16 18](https://user-images.githubusercontent.com/35394193/154470822-4bed2c0e-1427-452c-bb8d-9e80997eb011.png)

I added a Session Generator which lives on the Rig for now:
![Screenshot 2022-02-17 at 12 20 38](https://user-images.githubusercontent.com/35394193/154471266-36e38f1a-745d-4e78-8c97-806312a0bba0.png)

I added the Rig to both first and second scene, and named them '[UXF_Rig] in first scene' and  '[UXF_Rig] in second scene'

When going from first to second scene, you can see that the Session gets started and killed based on the first scene's SessionGenerator loading and unloading (which also unloads the Rig), and then only in the second scene does Awake get called...:
![Screenshot 2022-02-17 at 12 14 28](https://user-images.githubusercontent.com/35394193/154470368-4d022244-4855-436e-82ed-190405ba32b9.png)

I have my own DDOL class that I often use: 
![Screenshot 2022-02-17 at 12 22 33](https://user-images.githubusercontent.com/35394193/154471610-34185f18-755e-4ffb-a8dd-1eb47df31095.png)


Now if I add my own DDOL class to the Rig in the first scene (but not the second), you see that the first Rig is not destroyed, but the second Rig is based on the Instance checker already in UXF's Session: 
![Screenshot 2022-02-17 at 12 24 32](https://user-images.githubusercontent.com/35394193/154471833-b6827c31-772e-4c23-b27d-077b4c7bec66.png)

I don't mind keeping the Rig in the second scene for now. It works fine for my purposes. It's just that I'm curious, and have a tendency to get stuck on "this should work but it doesn't"-issues :).

**Comment by mrstruijk** [comment]
Now to your other point: Setting the Editor Options to 'Reload Scene' works wonders as well...!

This is without my own DDOL script enabled, but only having Reload Scene enabled:
![Screenshot 2022-02-17 at 12 32 20](https://user-images.githubusercontent.com/35394193/154473005-64550e10-e295-4101-b94c-cad45ca5134b.png)

With only Reload Domain enabled it doesn't work:
![Screenshot 2022-02-17 at 12 31 20](https://user-images.githubusercontent.com/35394193/154472886-52b527b6-3b06-4e1f-8e22-1f28dbfa002d.png)

Both enabled works too obviously.

**Comment by jackbrookes** [comment]
I'll look for a better solution to this.

**Comment by jackbrookes** [comment]
In UXF v2.4.2 you can now fix this with the UXF Wizard compatibility checker. In the future I hope this works without the need for these settings.

https://github.com/immersivecognition/unity-experiment-framework/wiki/Common-issues#general-compatibility.
