### ISSUE TITLE
Datapoints Not Editable in 2020.3.25f1

### ISSUE THREAD

**Issue by evankirkiles** [immersivecognition/unity-experiment-framework#115]
This is probably an issue with the SubjectNerd Reorderable list plugin, which is no longer being updated. Many of the tutorials display being able to edit the datapoints list, but this seems no longer possible in the current version of Unity. Rather, it looks like this without the ability to add a new item to the list.

![Screen Shot 2022-02-27 at 8 28 32 PM](https://user-images.githubusercontent.com/30581915/155909981-b64f9713-614b-4156-b5c6-5c9c72e4efa3.png)

**Comment by jackbrookes** [comment]
Hi - can you see if the latest version fixes your issue? I pushed some changes in 2.4.1 to address this.

https://github.com/immersivecognition/unity-experiment-framework/releases

**Comment by evankirkiles** [comment]
Works perfectly now, thank you so much!!!! 😁
