### ISSUE TITLE
Possible feature: screen ray tracker that allows tracking what is where & when on the screen

### ISSUE THREAD

**Issue by JAQuent** [immersivecognition/unity-experiment-framework#128]
I finally had time to work on a custom tracker called screenRayTracker and added it one of my repos with some instructions. what it can do and how it is use.  This can be found here: [https://github.com/JAQuent/scripts-for-unity3d/tree/master/screenRayTracker](https://github.com/JAQuent/scripts-for-unity3d/tree/master/screenRayTracker).

The idea is to get information about what is where & when on the screen. I think it could be of general interest and it would be great to get feedback from the community and hope that it can be useful to others. 

Looking forward hearing from you.

**Comment by jackbrookes** [comment]
Hey, I had a quick look and there are a couple of aspects of the code that would need to be tweaked to keep it consistent with the rest of UXF. If you fork UXF, add your code, and create a pull request I can review it properly and comment on each line and where we may need to make changes.
