### ISSUE TITLE
Why does my tracked object appear twice in my trial_result.csv?

### ISSUE THREAD

**Issue by JAQuent** [immersivecognition/unity-experiment-framework#131]
I have encountered a weird situation where all of a sudden my one tracked object appears twice in the `trial_result.csv`.  See

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Alex/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Alex/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

player_movement_location_0 | player_movement_location_1
-- | --
OLM_mainTask/test/S001/trackers/player_movement_T001.csv | OLM_mainTask/test/S001/trackers/player_movement_T001.csv

</body>

</html>

This didn't happen in old versions of my experiment. I've no idea why that is all of a sudden. 

1. I do not have two tracked objects:
![image](https://user-images.githubusercontent.com/17894303/169226971-6a451c61-c49e-475b-8bce-62f9e01614e2.png)

When I actually try to track it twice I get this error: 
> InvalidOperationException: Two or more trackers in the Tracked Objects field in the Session Inspector have the following object name and descriptor pair, please change the object name fields on the trackers to make them unique: player_movement

2. I do only have on instance of the script on my player game object:
![image](https://user-images.githubusercontent.com/17894303/169227118-06a12f5a-8bfa-4c92-a69d-283e037b5a82.png)

I mean on it's own this does not bother me too much but I a) don't understand why it is happening and b) I want to make sure that I am not saving things twice.

**Comment by jackbrookes** [comment]
This would only occur as far as I can tell if you have 2 data handlers. That's why they are marked `location_0` and `location_1`.

**Comment by JAQuent** [comment]
Ah, that make sense I use HTTP Post as well as the normal file saver. Thanks this is very reassuring.
