### ISSUE TITLE
Is there a way to run an animation after the last trial on Block?

### ISSUE THREAD

**Issue by rmib200** [immersivecognition/unity-experiment-framework#132]
I want to run an animation when the experiment reaches the last trial in each block but I can't seem to make it work. I tried using the OnSessionEnd, PreSessionEnd events to trigger the animation but it doesn't work. Is like the events occurs too fast. Maybe I'm messing up in something simple but I couldn't figure out completely. Any help would be really appreciated.

**Comment by jackbrookes** [comment]
OnSessionEnd works at the end of each session, not block. You need to use OnTrialEnd and check if it the final trial in the block:

```cs
// assign to OnTrialEnd
public void MyMethod(UXF.Trial trial)
{
    if (trial == trial.block.lastTrial)
    {
        // trigger animation
    }
}
```

**Comment by rmib200** [comment]
Thank you, it really helped set some things. But the error I'm still having is that the next block start too fast. Is there any way to control that?

**Comment by jackbrookes** [comment]
Of course, the next block begins whenever you begin the next trial. Somewhere, you must be starting the next trial, you could add a delay using `Invoke(...)` or a coroutine.
