### ISSUE TITLE
Scripting Runtime Version needed to be changed manually [Unity 2018.3.7]

### ISSUE THREAD

**Issue by eioe** [immersivecognition/unity-experiment-framework#14]
When importing UXF, the wizard would not open and I got a "missing reference" error. Once I manually set "Scripting Runtime Version" to 4.x, (+forced Unity restart), things would run smoothly. 
It seems like UXF was then trying to set the Runtime Version accordingly, but problems already occured earlier. 
As long as this cannot be fixed (or might be fixed with next Unity update), maybe put a brief info in the README/getting started section to save people like me (who don't have much insight) some time. :)

**Comment by eioe** [comment]
This info is actually already in the wiki under "common issues".

**Comment by jackbrookes** [comment]
Will investigate the NullReferenceException in the UXFWizard
