### ISSUE TITLE
[feature request] Add OnBlockBegin and OnBlockEnd events/actions

### ISSUE THREAD

**Issue by ahmed-shariff** [immersivecognition/unity-experiment-framework#141]
As the title suggests, there could be OnBlockBegin and OnBlockEnd events. In the absence of this feature, I am testing the beginning and end of a block inside the OnTrialBegin and OnTrialEnd events. 

If you think this could be a good addition let me know, I can work on it on my spare time.

**Comment by thefirstfloor** [comment]
That would be a nice addition. In our projects we use those a lot, I also made a workaround using the OnTrialBegin atm.
