### ISSUE TITLE
Show trial/block information and data while running experiment in a build project (not in editor)

### ISSUE THREAD

**Issue by allen6chen** [immersivecognition/unity-experiment-framework#144]
Hi Jake,

I'm curious to know how to open up the UXF Session Debugger tab in a build project. Is there a function I can use to call out the tab to appear? Or is there a way to see the previous, current, and future trials/blocks and the independent data associated with it during the trial in the build? 

I know in editor we can get access to Session(Script) in [UXF_Rig] to see the trial number and block number but is there a way to see these information after you build the project?

Thank you in advance

**Comment by jackbrookes** [comment]
Sorry this is not supported since the debugger is built using Unity Editor code.

Your best bet is to write some code that prints this information out, or write simple code to print this in a UI somewhere
