### ISSUE TITLE
Is there a way to change the start and end time to Unix Timestamps?

### ISSUE THREAD

**Issue by rmib200** [immersivecognition/unity-experiment-framework#145]
I was wondering if there is a way to change the value on the start and end time from seconds to Unix timestamps. So instead of having ms since the task started we could have Unix float time.
![image](https://user-images.githubusercontent.com/19299616/190448775-7d6adf70-9f60-4669-ad1c-2bb6ddffa475.png)
Thanks in advance for any help!

**Comment by jackbrookes** [comment]
No, but you can very easily add a new result with your timestamp, and save it to the trial results on start and end by hooking it into the session events.

**Comment by rmib200** [comment]
Worked like a charm. Thanks!
![image](https://user-images.githubusercontent.com/19299616/190456154-fd3d5435-8a2c-4a1a-9218-85302bc8f92d.png)
