### ISSUE TITLE
Session.End() quit the whole application

### ISSUE THREAD

**Issue by rmib200** [immersivecognition/unity-experiment-framework#146]
Hi, I want to end the experiment but not necessarily end the runtime after ending a session. Right now the app exits, or if I am in the Unity Editor to runtime ends. For example, I wanna show a menu and possibly go back to the experiment after calling Session.instance.End() . Is that possible?

**Comment by rmib200** [comment]
@jackbrookes hi, do you have any thoughts on this? :)

**Comment by jackbrookes** [comment]
There is no default behaviour in UXF that ends the application after a session. Perhaps you have a method hooked up to your `OnSessionEnd` event that quits the application when the session ends?
