### ISSUE TITLE
Unity Scene view, View Tool does not work after installing UXF

### ISSUE THREAD

**Issue by AntonLimhamn** [immersivecognition/unity-experiment-framework#164]
Working with the UXF Framework (v2.4.3) I ran into a strange problem. It is present in (at least) 2022.3.22f1 2022.3.32f1 2022.3.33f1 versions of Unity: When I install the UXF framework (JUST install), the View Tool in the Scene view does not work any more, The camera gizmo turns the scene alright, just the Hand movement does not work. It has something to do with System.Windows.Forms.dll : if I exclude it from the install, the View Tool works (but I get other problems). If I copy the same dll from the Unity Editor instead it does not help either. So there is something more to it...

**Comment by Juris-S** [comment]
I had the same issue which was picked-up and resolved by a Unity employee! Hats off to them for such a quick turnaround:

https://issuetracker.unity3d.com/issues/scene-view-camera-cannot-be-moved-when-using-the-mouse-wasd-keys-or-the-move-tool

**Comment by kajsaantonigelstrom** [comment]
Great. Thank you. Seems to work. Not with Version Control though, some version mis-match. I use git so I removed the package and all seems fine. Thank you again!
