### ISSUE TITLE
When, adding a new trial setting of type list<float>, type is not preserved.

### ISSUE THREAD

**Issue by performlabrit** [immersivecognition/unity-experiment-framework#28]
I am creating a new trial within a series of nested for loop and adding variables.
I then set a value to a type List<float>, consistent with the following example code.

```
Block block = UXF_Session.CreateBlock();
newTrial = block.CreateTrial();
new List<float> aListOfFloats = new List<float>{1.0f, 2.0f, 3.0f};
newTrial.settings.SetValue("aListOfFloats", aListOfFloats);
```

When I later try and retrieve this value from the trial settings dictionary, I get the error: (System.InvalidCastException: Specified cast is not valid.).

```
var tr = UXF_Session.CurrentTrial;
List<float>  aListOfFloats = tr.settings.GetFloatList("aListOfFloats");
```

Inspection via debugger shows that the variable is stored as a generic list.  I've played around, and the only way to retrieve the list seems to be through 

`var aListOfFloats = tr.settings.GetObject("aListOfFloats");`

A var, however, is not indexable.  I am still working on this.  I believe the temporary solution is to cast this to an iEnumerable using LinQ, but am still investigating option.  This does not, however, seem like the proper solution, which would involve UXF storing this as type list<float>, instead of as a generic list / object.

**Comment by jackbrookes** [comment]
A workaround should be:

```
var aListOfFloats = (List<float>) tr.settings.GetObject("aListOfFloats");
```

But I will investigate

**Comment by jackbrookes** [comment]
Fixed, issue was that `Get*List()` is designed to cast from the `List<object>`s that MiniJSON creates, rather than for settings created with `.SetValue`. Now these work in both cases.
