### ISSUE TITLE
Improve documentation on trial scheduling

### ISSUE THREAD

**Issue by gabrielDiaz-performlab** [immersivecognition/unity-experiment-framework#29]
As a new user, I find that documentation of the many functions related to trial "scheduling" (incrementing, ending, starting) to be a bit under-documented in both the tutorial and documentation.

I would make it clear that trials can be  "on" or "off,"  and I assume that this is what the "status" property is.

I would also clarify that the trial number is automatically incremented upon a call to trial.Begin(), or session.BeginNextTrial().

I assume, then, that data output is also started automatically upon trial.Begin().
 
- gD

**Comment by jackbrookes** [comment]
Yes it's correct that the session has a current session number, which is changed when a new trial begins. The session number is defined by the position of that trial in the `session.trials` list, that you would have specified when you generated your blocks. 
Yes trials are either on or off, but I think it's not normally useful to use this logic in your code. Best to manipulate your scene with the `OnTrialBegin` and `OnTrialEnd` events, and calls to `session.NextTrial.Begin()` & `session.CurentTrial.End()`.

If any specific parts of the wiki or tutorial are confusing you should be able to edit them and I will approve it!
