### ISSUE TITLE
Editing tracker list mid-experiment leads to problematic trialData.csv

### ISSUE THREAD

**Issue by performlabrit** [immersivecognition/unity-experiment-framework#30]
My experimental design involves different types of trials, with different needs for data recording.  As a result, I modify the session's tracker list mid-experiment.  This leads to issues with trialData.csv, which assumes a stable tracker list, where each tracker file is linked in its own column, which receives its own header at the start of the session. 

The issues is that these headers are invalid once the number of trackers is modified.

The simple fix would be to stop using a column per tracker, and instead switch to a SINGLE column output regardless of the number of trackers.  The column, which I will call, "Trackerlist" would list all data files associated with that trial in string format, with a non-comma delimiter between filenames.  Eg, "head_movement.csv; foot_movement.csv; tool_orientation.csv". 

This solution is an improvement in that it avoids having a CSV that changes the number of columns when the number of trackers changes.

**Comment by jackbrookes** [comment]
Whilst your solution is OK, I think it makes it complicated for simple experiments. One way to solve this in my experience is make a GameObject called e.g. "Tracker" with the PositionRotationTracker component attached, then you can just reparent this Tracker GameObject to the head, foot, tool etc. E.g.

```csharp
if (trialType == "foot")
{    
    tracker.transform.parent = foot.transform;
}
else if (trialType == "head")
{    
    tracker.transform.parent = head.transform;
}
...
```

**Comment by performlabrit** [comment]
This is still a bit limiting, as it assumes that you know all the trackers you will need at the beginning of the experiment. Jack, can you point me towards the code where the tracker's filenames are written out to the trial data file?

**Comment by jackbrookes** [comment]
At the end of each trial, this is called:
https://github.com/immersivecognition/unity-experiment-framework/blob/3716bf0018fcece530b65f2cfe77a09b430f4da0/Assets/UXF/Scripts/Etc/Trial.cs#L113-L119

Which calls this per tracker:
https://github.com/immersivecognition/unity-experiment-framework/blob/e09e4ce821763500d4d48e7aa23c23ad41c95c93/Assets/UXF/Scripts/Session.cs#L379-L403

**Comment by jackbrookes** [comment]
In general, I would prefer a simple approach rather than a complex approach that hurts most use cases, which I think splitting a string delimited by `;` does. For your exact issue where an unknown number of trackers are needed, you can actually write your own tracker class which collects data however it wants, and can be different on each trial. You would need to create a class which inherits from `Tracker` and implements all the methods. The `PositionRotationTracker` is an example of this:

https://github.com/immersivecognition/unity-experiment-framework/blob/3716bf0018fcece530b65f2cfe77a09b430f4da0/Assets/UXF/Scripts/PositionRotationTracker.cs

You could copy the above file but add public fields which point to the object(s) you are currently tracking, and change the data it spits out based on the content of the field.

**Comment by performlabrit** [comment]
?Thanks, Jack.  I'll see what I can do.


----------------------

Gabriel J. Diaz, Ph.D.
Associate Professor
Rochester Institute of Technology
Chester F. Carlson Center for Imaging Science

Founder of PerForM Labs
Click for demos.<https://www.cis.rit.edu/performlab/>

Office 2108, Building #76
Rochester, NY 14623
Office: (585) 475-6215<tel:(585)%20475-6215>
gabriel.diaz@rit.edu<mailto:gabriel.diaz@rit.edu>
________________________________

**Comment by jackbrookes** [comment]
@performlabrit I have news! I tested this out with the new "Ad Hoc Header Add" setting in the Session component, everything should work out of the box.

The way to do it is to edit the `session.trackedObjects` as the trial begins, and then remove that object from the list after the trial has ended. Something like this, assuming you have a reference to the "Foot" tracker in your script:

```csharp
// starting your trial
session.NextTrial.Begin();
session.trackedObjects.Add(foot);

...

// ending your trial
session.CurrentTrial.End();
session.trackedObjects.Remove(foot); // <-- IMPORTANT, REMOVE AFTER TRIAL ENDED

```

Of course you get something like this as the output, but I think this is preferable as it requires no further processing.

![image](https://user-images.githubusercontent.com/23621596/90425497-bb0c3d80-e0b7-11ea-840a-046db1598a76.png)

**Comment by performlabrit** [comment]
Jack, I believe I did try something like this.  This works within Unity, but presented some complications later on.  If my memory is correct, the issue is that the trackers/filenames specified in the CSV headers will apply to some rows/trials, but not others. Really, the tracker files need to be specified on a row-by-row basis in the trial results file, not once at the headers, for all rows.


If your proposed solution solves that problem, then we're all set.


In my particular use-case, I've just opted to have all trackers on, all the time.  Because trial types can differ qualitatively (e.g. some trials are for eye tracking calibration, others for performing a visual-motor task), each trial type will have tens of columns of "nan" data.


- gD


----------------------

Gabriel J. Diaz, Ph.D.
Associate Professor
Rochester Institute of Technology
Chester F. Carlson Center for Imaging Science

Founder of PerForM Labs
Click for demos.<https://www.cis.rit.edu/performlab/>

Office 2108, Building #76
Rochester, NY 14623
Office: (585) 475-6215<tel:(585)%20475-6215>
gabriel.diaz@rit.edu<mailto:gabriel.diaz@rit.edu>
________________________________

**Comment by performlabrit** [comment]
...or, maybe I'm misunderstanding the organization implied by that image.  Maybe the number of columns is indeed constant (as indicated by the top-row) and the repetitions in each column serve more as bools to indicate that the file is included.  If that's the case, then that works, too.

**Comment by jackbrookes** [comment]
There is a constant number of columns within a session. If the cell is blank, it just means that tracker was not active on that trial.

There would be a variable number of columns (across participants) if some participants did not experience some trials which had those trackers, correct. This is why the adhoc option is optional, because it requires a bit more thinking if you are importoring and merging lots of participants' data files.
