### ISSUE TITLE
Throw a warning/error when writing a Vector or List to trial_results

### ISSUE THREAD

**Issue by performlabrit** [immersivecognition/unity-experiment-framework#31]
Currently, a vector or list is written as a comma-delimited tuple, eg. (1,2,3), and associated with a single header, (e.g. "ObjectPosition_XYZ".  This is problematic when writing to a comma delimited file, since the values will be parsed across multiple columns as: "(1", "2", and "3)".   Consequently, there will be a mismatch between the number of headers and columns.

The simple fix is to throw an error when a Vector or List is passed in. 

A more robust solution would be to automatically parse iterables into multiple columns, e.g. ObjectPosition_XYZ_1, ObjectPosition_XYZ_2, ObjectPosition_XYZ_3

**Comment by jackbrookes** [comment]
For more explanation, this is built-in C#/Unity behaviour - UXF just calls the `.ToString()` method that exists on all objects. Sometimes these strings contain commas. 
You can get around this by converting to a string yourself, e.g.

```csharp
Vector3 myVec = new Vector3(1, 2, 3);
trial.result["observation"] = string.Format("{0};{1};{2}", myVec.x, myVec.x, myVec.x);
```
Or split into columns:
```csharp
Vector3 myVec = new Vector3(1, 2, 3);
trial.result["observation_x"] = myVec.x;
trial.result["observation_y"] = myVec.y;
trial.result["observation_z"] = myVec.z;
```

However perhaps UXF should try to help here by changing the commas to another character and throwing a warning.
