### ISSUE TITLE
NoSuchTrialException Error

### ISSUE THREAD

**Issue by kogrob** [immersivecognition/unity-experiment-framework#34]
Hello! 

I'd consider myself to be relatively new to Unity and C#, so I apologize in advance if this is a basic coding issue. 

I've been following along with the full tutorial and applying it to my own experiment, but for some reason, I can't get my experiment to start at all. The program loads, but before I click "start," I get the "There is no trial zero" error. Once I click "start," I then get the "There is no next trial" error. I've tried setting the number of trials as a set value within my code, as well as via my json settings file. Do you know of any possible situations that might be throwing this error? I didn't have this issue with other experimental setups, although I was able to run my experiments despite having the "there is no trial zero error." 

Thanks!

**Comment by jackbrookes** [comment]
This would trigger if you try to start the next trial e.g. with `BeginNextTrial()` before you have generated your trials. Perhaps show a screenshot of the items in the events of `On Session Begin`?

**Comment by kogrob** [comment]
![UXF Screenshot](https://user-images.githubusercontent.com/68101467/96392292-9850ef00-11f6-11eb-86d4-7d7f53c6a482
.PNG)
Here's a screenshot of the items that I have in `On Session Begin`
I eventually was able to get my experiment to run, but I'm still getting the NoSuchTrialException error. What ended up fixing things more or less was removing any instances of session.CurrentTrial.result[""] from my experiment generator class. One of my classes ends up having to access session.CurrentTrial to record some data, so the error is coming from that script. Do you have any suggestions on how I could ensure that all the trials are generated first before this class runs? Would I have to use a coroutine for this?

**Comment by jackbrookes** [comment]
See, you are running `BeginNextTrial` before `Generate`. These events run from top to bottom. Reorder them, putting `BeginNextTrial` at the bottom by grabbing them with the drag texture on the left side. Hope that helps!
![Untitled](https://user-images.githubusercontent.com/23621596/96422576-1a89e500-11f0-11eb-89fb-ac07acd148c8.png)
