### ISSUE TITLE
Add list element 'Settings to log' from script.

### ISSUE THREAD

**Issue by thefirstfloor** [immersivecognition/unity-experiment-framework#54]
Wiki "The Settings system allows researchers to pre-define parameters at the Session, Block or Trial level. These can be thought of as our independent variables. The settings to log is a list of settings that you wish to be recorded on each trial and added to the trial results output, specified using the Session component's inspector."

As far as I understand the docs, you can set a parameter on any level (block/trial) with _settings.SetValue("exampleParameter", 100)_, but cannot find a way to make this setting then also automatically logged as a column in the trial.csv file. 
Only way seems to be then also add the 'exampleParameter' to the inspectors 'Data collection' tab.
Or am I misunderstanding something?

**Comment by jackbrookes** [comment]
Yes that is the way to do it, type in the key name in this field.

You should also be able to add to this programmatically, if the key is variable:

```cs
session.settingsToLog.Add("exampleParameter");
```

You could also store as a result, it wont affect the output:

```cs
session.CurrentTrial.result["exampleParameter"] = session.CurrentTrial.GetInt("exampleParameter");
```

**Comment by thefirstfloor** [comment]
I prefer to define which settings are logged when setting up the session's sequence (based on the given settings), so before actually starting the session. When saving the output at end of trial, I then add the calculated outcomes as results. 
Feels more 'on point' that way.

I needed the session.settingsToLog.Add(key); to do that. 
Thanks!
