### ISSUE TITLE
Trial results are only saved to AWS when <= 25 trials

### ISSUE THREAD

**Issue by ischtz** [immersivecognition/unity-experiment-framework#55]
I noticed that trial results for longer experiments didn't get saved to DynamoDB, and learned that [BatchWriteItem is limited to 25 items](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html) at a time. Data for experiments with <= 25 trials is saved fine, but for >25 the BatchWriteItem call fails and nothing is stored to the TrialResults table (just confirmed this with 2.1.0 on Unity 2019.4.16f1 LTS).

My [quick and dirty solution](https://github.com/ischtz/unity-experiment-framework/commit/0532b7dfa25178659b49305a9ec3b45d9a89a92a) was to submit the data in batches of 25, which has been working fine in a running experiment so far. Let me know if a PR would be helpful!

**Comment by jackbrookes** [comment]
Thanks! I am shocked I didn't encounter this during testing. I will take a look.

**Comment by jackbrookes** [comment]
Released a fix.
