### ISSUE TITLE
Cannot reference Session to Sub State Machine Script

### ISSUE THREAD

**Issue by Francodibrotsy** [immersivecognition/unity-experiment-framework#58]
Hi

I'm programing a simple task with the tool of state machine behavior in unity. I did the session public variable, and I can see it in the inspector, but I cannot reference the UXF rig to the Session space.  

![Question](https://user-images.githubusercontent.com/62441433/104679455-7cad9580-56cc-11eb-99e3-5b05adbb0fdb.png)

The Script is simple but doesn't allow to drag and put the UXF rig on it. Do you know how I can fix that? Thanks!

**Comment by jackbrookes** [comment]
You cannot reference scene objects in a StateMachineBehaviour, this is an issue with Unity not UXF: 
https://answers.unity.com/questions/998692/cant-assign-active-gameobjects-to-public-variables.html

You could try `var session = FindObjectsOfType<UXF.Session>()` in your script, or somehow link the state machine to some other code that you write that is attached in your scene.
