### ISSUE TITLE
PPID Element - 'spontaneous' changes to title and input field

### ISSUE THREAD

**Issue by cathymacpherson** [immersivecognition/unity-experiment-framework#62]
Firstly, thanks for UXF - this is a wonderful framework that has helped me endlessly in the creation of unity-based experimental procedures. 

I have recently come across a slightly strange behaviour in the PPID Element. I can change the title and input field, however, this appears to revert to the original set-up 'spontaneously' (I can't find a pattern, though I'm sure one exists). This in itself isn't too problematic, however when this occurs the input field ceases to show any text entered by the user. That is, although the box allows the participant to type in their PPID (and the experiment will run successfully), this text is invisible. Interestingly, the modified PPID title box and input field will also often spontaneously reappear, and begin working again as normal.

I thought I may be inadvertently duplicating the box and overlaying multiple versions (thereby 'hiding' my changes), but this doesn't appear to be the case. Is there perhaps some code within UXF that is overriding any changes I make?

Apologies if this can be attributed simply to user error. I thought it was worth raising in case this is an unexpected behaviour.

**Comment by cathymacpherson** [comment]
Hi Jack,

Thanks for your quick response. 

I have been editing the PPID in the UI controller component, in the same way as the screenshot you provide. 

I have used the datapoints functionality successfully, so may just collect an ID there instead!

Thanks.

**Comment by jackbrookes** [comment]
Did you find a solution to your issue? 😃
